import type { DatabaseAdapter } from "@hono-cms/schema";
import { hashToken, generateToken, getTokenPrefix } from "./service/hashing";
import { API_KEYS_TABLE } from "./service/tokens";
import { ROLES_TABLE, type PermissionMatrix } from "./tables/roles";

export type BootstrapOptions = {
  /** Namespace tagged on the bootstrap key row. Defaults to `"root"`. */
  namespace?: string;
  /** Token prefix used when generating the bootstrap key. Defaults to `"sk_"`. */
  prefix?: string;
  /** Override the on-disk location of the bootstrap-key file. */
  filePath?: string;
  /** If true, also writes the raw key to stdout via console.log once. */
  printOnce?: boolean;
};

export type BootstrapHooks = {
  /**
   * When supplied, the plugin invokes this with the raw bootstrap key after
   * persistence and *does not* write the `.cms-bootstrap-key` file. Lets users
   * wire the key into a secret manager (Doppler, Vault, AWS SM, …).
   */
  onBootstrapKey?: (key: string) => void | Promise<void>;
};

export type RunBootstrapInput = {
  db: DatabaseAdapter;
  env?: Record<string, unknown>;
  options?: BootstrapOptions;
  hooks?: BootstrapHooks;
};

const BOOTSTRAP_BANNER = "# DO NOT COMMIT — generated by @hono-cms/auth-tokens on first run";

const DEFAULT_BOOTSTRAP_FILENAME = ".cms-bootstrap-key";

const ROOT_ROLE_NAME = "root";

const ROOT_ROLE_PERMISSIONS: PermissionMatrix = { "*": { "*": true } };

/**
 * Result returned by {@link runBootstrap}.
 *
 * `key` is only present when a fresh bootstrap key was generated this run;
 * callers can use it to display install instructions exactly once.
 */
export type BootstrapResult =
  | { kind: "skipped"; reason: "existing_keys" }
  | { kind: "generated"; key: string; tokenId: string; filePath?: string }
  | { kind: "generated_callback"; key: string; tokenId: string }
  | { kind: "generated_env"; key: string; tokenId: string };

/**
 * Run the first-launch bootstrap sequence.
 *
 * Steps in order:
 *
 *   1. If the `api_keys` table is non-empty, skip (idempotent re-installs are
 *      cheap; "no keys" is the only safe trigger).
 *   2. Ensure the `roles` table contains the `root` role with permissions-all.
 *   3. Generate a fresh raw key, hash it, insert the row.
 *   4. Deliver the raw key via, in priority order:
 *        a. user-supplied `onBootstrapKey` callback;
 *        b. write to `<cwd>/.cms-bootstrap-key` (file mode 0o600);
 *        c. if (a) and (b) are unavailable but `env.CMS_BOOTSTRAP_KEY` is set,
 *           the env value is treated as the desired raw token instead of
 *           generating a new one — useful for cold-deploys on read-only FS.
 *   5. If none of (a)–(c) works, throw a descriptive error so the operator
 *      knows to wire up one of the three channels.
 */
export async function runBootstrap(input: RunBootstrapInput): Promise<BootstrapResult> {
  const { db, env = {}, options = {}, hooks = {} } = input;

  // Step 1 — skip when keys already exist (any keys, even revoked).
  const existing = await db.list(API_KEYS_TABLE, { limit: 1 });
  if (existing.items.length > 0) {
    return { kind: "skipped", reason: "existing_keys" };
  }

  // Step 2 — seed the root role.
  await ensureRootRole(db);

  const namespace = options.namespace ?? "root";
  const prefix = options.prefix ?? "sk_";

  // Step 4a — user-supplied callback wins.
  if (hooks.onBootstrapKey) {
    const key = generateToken(prefix);
    const tokenId = await persistBootstrapKey(db, key, namespace);
    await hooks.onBootstrapKey(key);
    if (options.printOnce) console.log(key);
    return { kind: "generated_callback", key, tokenId };
  }

  // Step 4b — write the file, with the env fallback covering EROFS / no-fs cases.
  const fileSupport = await detectFilesystem();

  // Path the user explicitly requested overrides cwd detection.
  const explicitPath = options.filePath;

  if (fileSupport.available) {
    try {
      const key = generateToken(prefix);
      const tokenId = await persistBootstrapKey(db, key, namespace);
      const filePath = explicitPath ?? joinPath(fileSupport.cwd, DEFAULT_BOOTSTRAP_FILENAME);
      writeBootstrapFile(fileSupport.fs, filePath, key);
      if (options.printOnce) console.log(key);
      return { kind: "generated", key, tokenId, filePath };
    } catch (error) {
      if (!isReadOnlyFsError(error)) {
        // Existing-file refusal or other errors propagate to the caller — the
        // file refusal carries the descriptive path the operator needs to see.
        throw error;
      }
      // EROFS — fall through to the env path.
    }
  }

  // Step 4c — env fallback.
  const envKey = readBootstrapEnvKey(env);
  if (envKey) {
    const tokenId = await persistBootstrapKey(db, envKey, namespace);
    if (options.printOnce) console.log(envKey);
    return { kind: "generated_env", key: envKey, tokenId };
  }

  // Step 5 — no channel available.
  throw new Error(
    "@hono-cms/auth-tokens: no api_keys exist and no writable filesystem. " +
    "Set env.CMS_BOOTSTRAP_KEY=<sk_...> to seed the first key, or provide " +
    "opts.onBootstrapKey to deliver it via your own channel."
  );
}

/**
 * Ensure the `root` role exists in the `roles` table. Idempotent — a no-op
 * when a role named `"root"` is already present.
 */
async function ensureRootRole(db: DatabaseAdapter): Promise<void> {
  const existing = await db.list(ROLES_TABLE, { filters: { name: ROOT_ROLE_NAME }, limit: 1 });
  if (existing.items.length > 0) return;
  const now = new Date().toISOString();
  await db.create(ROLES_TABLE, {
    name: ROOT_ROLE_NAME,
    description: "Bootstrap super-admin role created by @hono-cms/auth-tokens",
    permissions: ROOT_ROLE_PERMISSIONS,
    createdAt: now,
    updatedAt: now
  });
}

async function persistBootstrapKey(
  db: DatabaseAdapter,
  key: string,
  namespace: string
): Promise<string> {
  const tokenHash = await hashToken(key);
  const tokenPrefix = getTokenPrefix(key);
  const now = new Date().toISOString();
  const NEVER = "2100-01-01T00:00:00.000Z";
  const row = await db.create(API_KEYS_TABLE, {
    tokenHash,
    tokenPrefix,
    namespace,
    name: "bootstrap",
    metadata: { bootstrap: true },
    expiresAt: NEVER,
    maxIdleMs: 0,
    lastUsedAt: now,
    revoked: false,
    replacedBy: null
  });
  return row.id;
}

type FilesystemDetection =
  | { available: true; cwd: string; fs: FsLike }
  | { available: false; cwd: string };

/**
 * Detect whether we can write to the current working directory.
 *
 * Critically, all `process` access happens *behind* the `typeof process` guard
 * — under strict ESM, a bare `process.cwd()` raises `ReferenceError` that
 * cannot be caught by a try/catch around the call site (the binding error
 * happens at parse-time of the enclosing expression on some engines). This
 * mirrors the runtime-probe pattern at
 * `packages/adapter-postgres/src/index.ts:50`.
 *
 * `node:fs` is dynamic-imported so bundles targeting Workers / Deno / Edge
 * — environments without a usable `fs` — see this branch as unreachable
 * (a static import would force them to ship the polyfill or fail to build).
 */
async function detectFilesystem(): Promise<FilesystemDetection> {
  if (typeof process === "undefined") return { available: false, cwd: "" };
  if (typeof process.cwd !== "function") return { available: false, cwd: "" };
  let cwd: string;
  try {
    cwd = process.cwd();
  } catch {
    return { available: false, cwd: "" };
  }
  try {
    const mod = (await import("node:fs")) as unknown as FsLike;
    if (typeof mod.writeFileSync !== "function") return { available: false, cwd };
    return { available: true, cwd, fs: mod };
  } catch {
    return { available: false, cwd };
  }
}

type FsLike = {
  writeFileSync: (path: string, data: string, options?: { mode?: number }) => void;
  existsSync?: (path: string) => boolean;
};

function writeBootstrapFile(fs: FsLike, filePath: string, key: string): void {
  if (fs.existsSync?.(filePath)) {
    throw new Error(
      `@hono-cms/auth-tokens: refusing to overwrite existing bootstrap-key file at "${filePath}". ` +
      "Delete or move the file if you are intentionally rotating the key."
    );
  }
  const body = `${BOOTSTRAP_BANNER}\n${key}\n`;
  fs.writeFileSync(filePath, body, { mode: 0o600 });
}

function joinPath(dir: string, name: string): string {
  if (!dir) return name;
  return dir.endsWith("/") ? `${dir}${name}` : `${dir}/${name}`;
}

function isReadOnlyFsError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;
  const code = (error as { code?: unknown }).code;
  return code === "EROFS" || code === "EACCES";
}

function readBootstrapEnvKey(env: Record<string, unknown>): string | undefined {
  const fromEnv = env["CMS_BOOTSTRAP_KEY"];
  if (typeof fromEnv === "string" && fromEnv.length > 0) return fromEnv;
  if (typeof process !== "undefined") {
    const fromProcess = process.env?.CMS_BOOTSTRAP_KEY;
    if (typeof fromProcess === "string" && fromProcess.length > 0) return fromProcess;
  }
  return undefined;
}
