import { existsSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createMemoryDatabase } from "@hono-cms/adapter-memory";
import type { CMSCollections } from "@hono-cms/schema";
import { runBootstrap } from "../bootstrap";
import { hashToken } from "../service/hashing";
import { API_KEYS_TABLE } from "../service/tokens";
import { ROLES_TABLE, type RoleRow } from "../tables/roles";
import type { ApiKeyRow } from "../service/types";

function makeDb() {
  return createMemoryDatabase({ provider: "memory", collections: {} as CMSCollections });
}

let tmpDir: string;
let savedCwd: () => string;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "cms-bootstrap-test-"));
  savedCwd = process.cwd;
  process.cwd = () => tmpDir;
});

afterEach(() => {
  process.cwd = savedCwd;
  if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true, force: true });
});

describe("runBootstrap — writable filesystem path", () => {
  it("generates a key + writes <cwd>/.cms-bootstrap-key with 0o600 and DO NOT COMMIT banner", async () => {
    const db = makeDb();
    const result = await runBootstrap({ db });
    expect(result.kind).toBe("generated");
    if (result.kind !== "generated") return;

    const expectedPath = join(tmpDir, ".cms-bootstrap-key");
    expect(result.filePath).toBe(expectedPath);
    expect(existsSync(expectedPath)).toBe(true);

    const stats = statSync(expectedPath);
    // Mode mask off the file-type bits; check the owner-only rwx pattern.
    expect(stats.mode & 0o777).toBe(0o600);

    const body = readFileSync(expectedPath, "utf-8");
    const [banner, key, ...rest] = body.split("\n");
    expect(banner).toBe("# DO NOT COMMIT — generated by @hono-cms/auth-tokens on first run");
    expect(key).toBe(result.key);
    // Trailing newline → split() leaves an empty final element; tolerate one.
    expect(rest.length).toBeLessThanOrEqual(1);
  });

  it("persists the key as a hashed row in api_keys", async () => {
    const db = makeDb();
    const result = await runBootstrap({ db });
    if (result.kind !== "generated") throw new Error("expected generated kind");

    const rows = (await db.list(API_KEYS_TABLE, { limit: 10 })).items as ApiKeyRow[];
    expect(rows).toHaveLength(1);
    const expectedHash = await hashToken(result.key);
    expect(rows[0]?.tokenHash).toBe(expectedHash);
    expect(rows[0]?.namespace).toBe("root");
  });

  it("also seeds the root role with permissions-all", async () => {
    const db = makeDb();
    await runBootstrap({ db });
    const rows = (await db.list(ROLES_TABLE, { limit: 10 })).items as RoleRow[];
    const root = rows.find((r) => r.name === "root");
    expect(root).toBeDefined();
    expect(root?.permissions).toEqual({ "*": { "*": true } });
  });

  it("skips bootstrap when api_keys is non-empty", async () => {
    const db = makeDb();
    await runBootstrap({ db });
    const second = await runBootstrap({ db });
    expect(second).toEqual({ kind: "skipped", reason: "existing_keys" });
    // File should still only exist once (we didn't touch it second time).
    expect(existsSync(join(tmpDir, ".cms-bootstrap-key"))).toBe(true);
  });

  it("refuses to overwrite an existing .cms-bootstrap-key file", async () => {
    const existingPath = join(tmpDir, ".cms-bootstrap-key");
    writeFileSync(existingPath, "do not touch", { mode: 0o600 });
    const db = makeDb();
    await expect(runBootstrap({ db })).rejects.toThrow(/refusing to overwrite/);
    // The file we placed earlier is intact.
    expect(readFileSync(existingPath, "utf-8")).toBe("do not touch");
  });
});

describe("runBootstrap — onBootstrapKey callback", () => {
  it("invokes the callback with the raw key and does not write a file", async () => {
    const db = makeDb();
    const seen: string[] = [];
    const result = await runBootstrap({
      db,
      hooks: { onBootstrapKey: (key) => { seen.push(key); } }
    });
    expect(result.kind).toBe("generated_callback");
    expect(seen).toHaveLength(1);
    expect(seen[0]?.startsWith("sk_")).toBe(true);
    expect(existsSync(join(tmpDir, ".cms-bootstrap-key"))).toBe(false);
  });
});

describe("runBootstrap — serverless / no-fs path", () => {
  it("emits a descriptive error (not ReferenceError) when process is undefined and no env key set", async () => {
    const db = makeDb();
    // Simulate a Workers-like env where `process` is undefined.
    const realProcess = globalThis.process;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).process = undefined;
    try {
      await expect(runBootstrap({ db, env: {} })).rejects.toThrowError(/CMS_BOOTSTRAP_KEY/);
    } finally {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (globalThis as any).process = realProcess;
    }
  });

  it("uses env.CMS_BOOTSTRAP_KEY when filesystem write fails with EROFS", async () => {
    const db = makeDb();
    // Point cwd at a non-existent directory so writeFileSync raises ENOENT.
    // Then map ENOENT-style errors as "EROFS-equivalent" via the fallback
    // by also setting `code: "EROFS"` on the synthetic readonly error.
    //
    // We achieve EROFS by setting cwd to a known read-only system location.
    // /System is read-only on macOS; /proc/self on Linux. For portability we
    // wrap process.cwd to a fake path and then spy on the underlying writeFile
    // by replacing the module export through globalThis — vitest can't redefine
    // ESM exports, so instead we exercise the error via an existing-file
    // collision shaped to look like EROFS. Concretely: pre-create the file
    // and modify the mock error map. Simpler: use a read-only directory.
    //
    // Approach: chmod the tmpdir to 0o500 (read+exec, no write). writeFileSync
    // returns EACCES which our isReadOnlyFsError accepts as fallback.
    const { chmodSync } = await import("node:fs");
    chmodSync(tmpDir, 0o500);
    try {
      const result = await runBootstrap({
        db,
        env: { CMS_BOOTSTRAP_KEY: "sk_supplied_via_env_token_for_testing_xxxxxxxxxx" }
      });
      expect(result.kind).toBe("generated_env");
      if (result.kind === "generated_env") {
        expect(result.key).toBe("sk_supplied_via_env_token_for_testing_xxxxxxxxxx");
      }
    } finally {
      // Restore write permissions so afterEach cleanup can rm -r.
      chmodSync(tmpDir, 0o700);
    }
  });
});

describe("runBootstrap — custom options", () => {
  it("honors a custom namespace", async () => {
    const db = makeDb();
    await runBootstrap({ db, options: { namespace: "admin" } });
    const rows = (await db.list(API_KEYS_TABLE, { limit: 10 })).items as ApiKeyRow[];
    expect(rows[0]?.namespace).toBe("admin");
  });

  it("honors a custom token prefix", async () => {
    const db = makeDb();
    const result = await runBootstrap({ db, options: { prefix: "tk_" } });
    if (result.kind !== "generated") throw new Error("expected generated");
    expect(result.key.startsWith("tk_")).toBe(true);
  });

  it("writes to a custom filePath when supplied", async () => {
    const db = makeDb();
    const customPath = join(tmpDir, "custom-key");
    const result = await runBootstrap({ db, options: { filePath: customPath } });
    expect(result.kind).toBe("generated");
    expect(existsSync(customPath)).toBe(true);
  });
});
