import type { CMSCollections, CollectionDefinition, FieldDefinition, FieldsDefinition, RelationCardinality, RelationField } from "./index";

type AnyRelationField = RelationField<string, RelationCardinality, boolean>;

type JoinTable = {
  tableName: string;
  exportName: string;
  leftCollection: string;
  rightCollection: string;
};

export type DrizzleDialect = "sqlite" | "pg";

export type GenerateDrizzleSchemaOptions = {
  dialect?: DrizzleDialect;
  includeLocaleVariants?: boolean;
  includeAuditLog?: boolean;
};

type DrizzleRenderer = {
  dialect: DrizzleDialect;
  table: string;
  imports: string;
};

export function generateDrizzleSchema(collections: CMSCollections, options: GenerateDrizzleSchemaOptions = {}): string {
  const renderer = drizzleRenderer(options.dialect ?? "sqlite");
  const ordered = Object.values(collections).sort((a, b) => a.name.localeCompare(b.name));
  const joinTables = collectJoinTables(ordered);
  const includeLocaleVariants = options.includeLocaleVariants ?? ordered.some((collection) => collection.options.i18n);
  const includeAuditLog = options.includeAuditLog ?? true;
  const lines = [
    "/* eslint-disable */",
    "// Generated by @hono-cms/schema. Do not edit by hand.",
    "import { relations } from \"drizzle-orm\";",
    renderer.imports,
    "import { createId } from \"@paralleldrive/cuid2\";",
    ""
  ];

  for (const collection of ordered) {
    lines.push(renderTable(collection, renderer), "");
  }
  for (const joinTable of joinTables) {
    lines.push(renderJoinTable(joinTable, renderer), "");
  }
  if (includeLocaleVariants) {
    lines.push(renderLocaleVariantsTable(renderer), "");
  }
  if (includeAuditLog) {
    lines.push(renderAuditLogTable(renderer), "");
  }
  for (const collection of ordered) {
    lines.push(renderRelations(collection, joinTables), "");
  }
  for (const joinTable of joinTables) {
    lines.push(renderJoinTableRelations(joinTable), "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function drizzleRenderer(dialect: DrizzleDialect): DrizzleRenderer {
  if (dialect === "pg") {
    return {
      dialect,
      table: "pgTable",
      imports: "import { boolean, index, integer, jsonb, pgTable, primaryKey, real, text, timestamp, uniqueIndex, varchar } from \"drizzle-orm/pg-core\";"
    };
  }
  return {
    dialect,
    table: "sqliteTable",
    imports: "import { index, integer, primaryKey, real, sqliteTable, text, uniqueIndex } from \"drizzle-orm/sqlite-core\";"
  };
}

function renderTable(collection: CollectionDefinition<string, FieldsDefinition>, renderer: DrizzleRenderer): string {
  const fields = Object.entries(collection.fields).sort(([a], [b]) => a.localeCompare(b));
  const columns = [
    `  id: ${idColumn(renderer)}.primaryKey().$defaultFn(() => createId()),`,
    ...fields.flatMap(([fieldName, field]) => renderFieldColumns(collection.name, fieldName, field, renderer)),
    ...(collection.options.draftAndPublish ? [
      `  publishedAt: ${timestampColumn("published_at", renderer)},`,
      `  status: ${statusColumn(renderer)}.notNull().default("draft"),`
    ] : []),
    ...(collection.options.i18n ? [`  locale: ${varcharColumn("locale", 10, renderer)},`] : []),
    `  createdAt: ${timestampColumn("created_at", renderer)}.notNull(),`,
    `  updatedAt: ${timestampColumn("updated_at", renderer)}.notNull(),`,
    `  createdBy: ${idColumn(renderer, "created_by")},`,
    `  updatedBy: ${idColumn(renderer, "updated_by")},`
  ];
  const indexes = fields.flatMap(([fieldName, field]) => renderIndexes(collection.name, fieldName, field));
  const indexBlock = indexes.length
    ? `, (table) => ({\n${indexes.map((source) => `  ${source}`).join(",\n")}\n})`
    : "";

  return [
    `export const ${tableExport(collection.name)} = ${renderer.table}(${JSON.stringify(collection.name)}, {`,
    ...columns,
    `}${indexBlock});`
  ].join("\n");
}

function renderFieldColumns(collection: string, fieldName: string, field: FieldDefinition, renderer: DrizzleRenderer): string[] {
  if (field.kind === "relation") {
    if (!ownsRelationColumn(field)) return [];
    const onDelete = field.onDelete ?? "restrict";
    const column = withColumnModifiers(
      `${idColumn(renderer, `${toSnakeCase(fieldName)}_id`)}.references(() => ${tableExport(field.target)}.id, { onDelete: ${JSON.stringify(onDelete)} })`,
      field
    );
    return [`  ${toIdentifier(`${fieldName}Id`)}: ${column},`];
  }
  if (field.kind === "media") {
    return [
      `  ${toIdentifier(`${fieldName}Id`)}: ${withColumnModifiers(idColumn(renderer, `${toSnakeCase(fieldName)}_id`), field)},`,
      `  ${toIdentifier(`${fieldName}Meta`)}: ${jsonColumn(`${toSnakeCase(fieldName)}_meta`, renderer)},`
    ];
  }
  if (field.kind === "component" || field.kind === "dynamiczone") {
    // Components and dynamic zones are stored as JSON (jsonb on pg, text mode:"json" on sqlite).
    // Strapi normalizes these into separate tables; we deliberately keep them embedded to avoid
    // explosion in relational complexity. Future work: optional normalized-table mode.
    return [`  ${toIdentifier(fieldName)}: ${withColumnModifiers(jsonColumn(toSnakeCase(fieldName), renderer), field)},`];
  }
  return [`  ${toIdentifier(fieldName)}: ${withColumnModifiers(baseColumn(fieldName, field, renderer), field)},`];
}

function renderIndexes(collection: string, fieldName: string, field: FieldDefinition): string[] {
  if (field.kind === "uid") {
    return [`${toIdentifier(`${fieldName}Idx`)}: index(${JSON.stringify(`${collection}_${toSnakeCase(fieldName)}_idx`)}).on(table.${toIdentifier(fieldName)})`];
  }
  if (field.kind === "relation" && ownsRelationColumn(field)) {
    return [`${toIdentifier(`${fieldName}IdIdx`)}: index(${JSON.stringify(`${collection}_${toSnakeCase(fieldName)}_id_idx`)}).on(table.${toIdentifier(`${fieldName}Id`)})`];
  }
  return [];
}

function baseColumn(fieldName: string, field: FieldDefinition, renderer: DrizzleRenderer): string {
  const columnName = JSON.stringify(toSnakeCase(fieldName));
  switch (field.kind) {
    case "string":
      return varcharColumn(toSnakeCase(fieldName), field.max ?? 255, renderer);
    case "text":
    case "richtext":
    case "password":
      return `text(${columnName})`;
    case "number":
      return field.int ? `integer(${columnName})` : `real(${columnName})`;
    case "boolean":
      return renderer.dialect === "pg" ? `boolean(${columnName})` : `integer(${columnName}, { mode: "boolean" })`;
    case "datetime":
      return timestampColumn(toSnakeCase(fieldName), renderer);
    case "date":
    case "time":
      return `text(${columnName})`;
    case "json":
      return jsonColumn(toSnakeCase(fieldName), renderer);
    case "email":
    case "uid":
      return varcharColumn(toSnakeCase(fieldName), 255, renderer);
    case "url":
      return varcharColumn(toSnakeCase(fieldName), 2048, renderer);
    case "enum":
      return renderer.dialect === "pg"
        ? `varchar(${columnName}, { length: 255, enum: ${renderStringArray([...field.values])} })`
        : `text(${columnName}, { enum: ${renderStringArray([...field.values])} })`;
    case "media":
    case "relation":
    case "component":
    case "dynamiczone":
      throw new Error(`${field.kind} fields are rendered by renderFieldColumns.`);
  }
}

function withColumnModifiers(source: string, field: FieldDefinition): string {
  let column = source;
  if (field.required) column += ".notNull()";
  if (field.unique) column += ".unique()";
  if (field.default !== undefined) column += `.default(${JSON.stringify(field.default)})`;
  return column;
}

function collectJoinTables(collections: Array<CollectionDefinition<string, FieldsDefinition>>): JoinTable[] {
  const joins = new Map<string, JoinTable>();
  for (const collection of collections) {
    for (const field of Object.values(collection.fields)) {
      if (field.kind !== "relation" || !isManyToMany(field)) continue;
      const pair = [collection.name, field.target].sort((a, b) => a.localeCompare(b)) as [string, string];
      const [leftCollection, rightCollection] = pair;
      const tableName = `${toSnakeCase(leftCollection)}_${toSnakeCase(rightCollection)}`;
      joins.set(tableName, {
        tableName,
        exportName: toIdentifier(`${leftCollection}_${rightCollection}Table`),
        leftCollection,
        rightCollection
      });
    }
  }
  return [...joins.values()].sort((a, b) => a.tableName.localeCompare(b.tableName));
}

function renderJoinTable(joinTable: JoinTable, renderer: DrizzleRenderer): string {
  const columns = joinTableColumns(joinTable);
  return [
    `export const ${joinTable.exportName} = ${renderer.table}(${JSON.stringify(joinTable.tableName)}, {`,
    `  ${columns.leftId}: ${idColumn(renderer, columns.leftColumn)}.notNull().references(() => ${tableExport(joinTable.leftCollection)}.id, { onDelete: "cascade" }),`,
    `  ${columns.rightId}: ${idColumn(renderer, columns.rightColumn)}.notNull().references(() => ${tableExport(joinTable.rightCollection)}.id, { onDelete: "cascade" }),`,
    `}, (table) => ({`,
    `  pk: primaryKey({ columns: [table.${columns.leftId}, table.${columns.rightId}] }),`,
    `}));`
  ].join("\n");
}

function idColumn(renderer: DrizzleRenderer, name = "id"): string {
  return varcharColumn(name, 24, renderer);
}

function varcharColumn(name: string, length: number, renderer: DrizzleRenderer): string {
  const columnName = JSON.stringify(name);
  return renderer.dialect === "pg" ? `varchar(${columnName}, { length: ${length} })` : `text(${columnName}, { length: ${length} })`;
}

function timestampColumn(name: string, renderer: DrizzleRenderer): string {
  const columnName = JSON.stringify(name);
  return renderer.dialect === "pg" ? `timestamp(${columnName}, { mode: "date" })` : `integer(${columnName}, { mode: "timestamp" })`;
}

function statusColumn(renderer: DrizzleRenderer): string {
  return renderer.dialect === "pg"
    ? `varchar("status", { length: 16, enum: ["draft", "published"] })`
    : `text("status", { enum: ["draft", "published"] })`;
}

function jsonColumn(name: string, renderer: DrizzleRenderer): string {
  const columnName = JSON.stringify(name);
  return renderer.dialect === "pg" ? `jsonb(${columnName})` : `text(${columnName}, { mode: "json" })`;
}

function renderRelations(collection: CollectionDefinition<string, FieldsDefinition>, joinTables: JoinTable[]): string {
  const relationsForCollection = Object.entries(collection.fields)
    .sort(([a], [b]) => a.localeCompare(b))
    .filter(([, field]) => field.kind === "relation")
    .map(([fieldName, field]) => renderRelationEntry(collection.name, fieldName, field as AnyRelationField, joinTables))
    .filter(Boolean);

  return [
    `export const ${toIdentifier(`${collection.name}Relations`)} = relations(${tableExport(collection.name)}, ({ one, many }) => ({`,
    ...relationsForCollection.map((entry) => `  ${entry},`),
    `}));`
  ].join("\n");
}

function renderRelationEntry(collection: string, fieldName: string, field: AnyRelationField, joinTables: JoinTable[]): string | null {
  if (ownsRelationColumn(field)) {
    return `${toIdentifier(fieldName)}: one(${tableExport(field.target)}, { fields: [${tableExport(collection)}.${toIdentifier(`${fieldName}Id`)}], references: [${tableExport(field.target)}.id] })`;
  }
  if (isManyToMany(field)) {
    const joinTable = findJoinTable(collection, field.target, joinTables);
    return joinTable ? `${toIdentifier(fieldName)}: many(${joinTable.exportName})` : null;
  }
  return `${toIdentifier(fieldName)}: many(${tableExport(field.target)})`;
}

function renderJoinTableRelations(joinTable: JoinTable): string {
  const columns = joinTableColumns(joinTable);
  return [
    `export const ${toIdentifier(`${joinTable.tableName}Relations`)} = relations(${joinTable.exportName}, ({ one }) => ({`,
    `  ${columns.leftRelation}: one(${tableExport(joinTable.leftCollection)}, { fields: [${joinTable.exportName}.${columns.leftId}], references: [${tableExport(joinTable.leftCollection)}.id] }),`,
    `  ${columns.rightRelation}: one(${tableExport(joinTable.rightCollection)}, { fields: [${joinTable.exportName}.${columns.rightId}], references: [${tableExport(joinTable.rightCollection)}.id] }),`,
    `}));`
  ].join("\n");
}

function joinTableColumns(joinTable: JoinTable): {
  leftColumn: string;
  rightColumn: string;
  leftId: string;
  rightId: string;
  leftRelation: string;
  rightRelation: string;
} {
  const selfReferential = joinTable.leftCollection === joinTable.rightCollection;
  if (selfReferential) {
    return {
      leftColumn: "left_id",
      rightColumn: "right_id",
      leftId: "leftId",
      rightId: "rightId",
      leftRelation: "left",
      rightRelation: "right"
    };
  }
  const leftName = singularize(joinTable.leftCollection);
  const rightName = singularize(joinTable.rightCollection);
  return {
    leftColumn: `${leftName}_id`,
    rightColumn: `${rightName}_id`,
    leftId: toIdentifier(`${leftName}Id`),
    rightId: toIdentifier(`${rightName}Id`),
    leftRelation: toIdentifier(leftName),
    rightRelation: toIdentifier(rightName)
  };
}

function findJoinTable(source: string, target: string, joinTables: JoinTable[]): JoinTable | undefined {
  const [leftCollection, rightCollection] = [source, target].sort((a, b) => a.localeCompare(b)) as [string, string];
  return joinTables.find((joinTable) => joinTable.leftCollection === leftCollection && joinTable.rightCollection === rightCollection);
}

function ownsRelationColumn(field: AnyRelationField): boolean {
  return field.cardinality === "one" || field.cardinality === "many-to-one" || field.cardinality === "one-to-one";
}

function isManyToMany(field: AnyRelationField): boolean {
  return field.cardinality === "many-to-many";
}

function tableExport(collection: string): string {
  return toIdentifier(`${collection}Table`);
}

function toIdentifier(value: string): string {
  const identifier = value.replace(/[-_\s]+([a-zA-Z0-9])/g, (_, char: string) => char.toUpperCase()).replace(/[^a-zA-Z0-9_$]/g, "");
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function toSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .toLowerCase();
}

function singularize(value: string): string {
  return value.endsWith("ies") ? `${value.slice(0, -3)}y` : value.endsWith("s") ? value.slice(0, -1) : value;
}

function renderStringArray(values: string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

function renderLocaleVariantsTable(renderer: DrizzleRenderer): string {
  return [
    `export const localeVariantsTable = ${renderer.table}("locale_variants", {`,
    `  id: text("id").primaryKey(),`,
    `  collection: text("collection").notNull(),`,
    `  documentId: text("document_id").notNull(),`,
    `  locale: text("locale").notNull(),`,
    `  fields: text("fields").notNull(),`,
    `  status: text("status", { enum: ["pending", "in_progress", "complete", "error"] }).notNull(),`,
    `  translatedBy: text("translated_by", { enum: ["ai", "human", "pending"] }).notNull(),`,
    `  sourceUpdatedAt: text("source_updated_at"),`,
    `  error: text("error"),`,
    `  provider: text("provider"),`,
    `  translatedAt: text("translated_at"),`,
    `  createdAt: text("created_at").notNull(),`,
    `  updatedAt: text("updated_at").notNull(),`,
    `}, (table) => ({`,
    `  collectionDocumentLocaleUnique: uniqueIndex("locale_variants_collection_document_locale_uq").on(table.collection, table.documentId, table.locale),`,
    `}));`
  ].join("\n");
}

function renderAuditLogTable(renderer: DrizzleRenderer): string {
  return [
    `export const auditLogTable = ${renderer.table}("audit_log", {`,
    `  id: text("id").primaryKey(),`,
    `  operation: text("operation").notNull(),`,
    `  collection: text("collection"),`,
    `  documentId: text("document_id"),`,
    `  actorId: text("actor_id"),`,
    `  actorRoles: text("actor_roles").notNull(),`,
    `  requestId: text("request_id").notNull(),`,
    `  diffBefore: text("diff_before"),`,
    `  diffAfter: text("diff_after"),`,
    `  createdAt: text("created_at").notNull(),`,
    `}, (table) => ({`,
    `  // Composite indexes for the canonical filter+order shapes; Plan 014 U1.`,
    `  createdAtIdx: index("audit_log_created_at_idx").on(table.createdAt),`,
    `  collectionOpCreatedIdx: index("audit_log_collection_op_created_idx").on(table.collection, table.operation, table.createdAt),`,
    `  documentCreatedIdx: index("audit_log_document_created_idx").on(table.documentId, table.createdAt),`,
    `  actorCreatedIdx: index("audit_log_actor_created_idx").on(table.actorId, table.createdAt),`,
    `}));`
  ].join("\n");
}
