import type { CollectionDefinition, CollectionOptions, FieldDefinition, FieldsDefinition } from "./index";

export type CollectionFileOptions = {
  importPath?: string;
};

export function generateCollectionFile(
  collection: CollectionDefinition<string, FieldsDefinition>,
  options: CollectionFileOptions = {}
): string {
  const importPath = options.importPath ?? "@hono-cms/schema";
  const variableName = toIdentifier(collection.name);
  const fieldsSource = renderFields(collection.fields);
  const optionsSource = renderCollectionOptions(collection.options);
  const args = [
    JSON.stringify(collection.name),
    fieldsSource,
    ...(optionsSource ? [optionsSource] : [])
  ];

  return [
    "/* eslint-disable */",
    "// Generated by @hono-cms/schema. Do not edit by hand.",
    `import { defineCollection, fields } from ${JSON.stringify(importPath)};`,
    "",
    `export const ${variableName} = defineCollection(`,
    indent(args.join(",\n"), 2),
    ");",
    "",
    `export default ${variableName};`,
    ""
  ].join("\n");
}

function renderFields(fields: FieldsDefinition): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) return "{}";
  return [
    "{",
    ...entries.map(([name, field]) => `${indent(`${JSON.stringify(name)}: ${renderField(field)}`, 2)},`),
    "}"
  ].join("\n");
}

function renderField(field: FieldDefinition): string {
  switch (field.kind) {
    case "enum": {
      const config = renderObject(omitKeys(field, ["kind", "values"]));
      return config ? `fields.enum(${renderArray([...field.values])}, ${config})` : `fields.enum(${renderArray([...field.values])})`;
    }
    case "relation": {
      const config = renderObject(omitKeys(field, ["kind", "target", "cardinality"]));
      return config
        ? `fields.relation(${JSON.stringify(field.target)}, ${JSON.stringify(field.cardinality)}, ${config})`
        : `fields.relation(${JSON.stringify(field.target)}, ${JSON.stringify(field.cardinality)})`;
    }
    default: {
      const config = renderObject(omitKeys(field, ["kind"]));
      return config ? `fields.${field.kind}(${config})` : `fields.${field.kind}()`;
    }
  }
}

function renderCollectionOptions(options: CollectionOptions): string {
  return renderObject(options);
}

function renderObject(value: Record<string, unknown>): string {
  const entries = Object.entries(value)
    .filter(([, entry]) => entry !== undefined && entry !== false)
    .sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) return "";
  return [
    "{",
    ...entries.map(([key, entry]) => `${indent(`${JSON.stringify(key)}: ${renderValue(entry)}`, 2)},`),
    "}"
  ].join("\n");
}

function renderValue(value: unknown): string {
  if (Array.isArray(value)) return renderArray(value);
  if (value && typeof value === "object") return renderObject(value as Record<string, unknown>);
  return JSON.stringify(value);
}

function renderArray(values: readonly unknown[]): string {
  return `[${values.map(renderValue).join(", ")}]`;
}

function omitKeys<T extends Record<string, unknown>>(value: T, keys: readonly string[]): Record<string, unknown> {
  const omitted = new Set(keys);
  return Object.fromEntries(Object.entries(value).filter(([key]) => !omitted.has(key)));
}

function indent(source: string, spaces: number): string {
  const prefix = " ".repeat(spaces);
  return source.split("\n").map((line) => line ? `${prefix}${line}` : line).join("\n");
}

function toIdentifier(name: string): string {
  const identifier = name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase()).replace(/[^a-zA-Z0-9_$]/g, "");
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `collection${identifier}`;
}
