/* eslint-disable */
// Generated by @hono-cms/schema. Do not edit by hand.
import { defineCollection, fields } from "@hono-cms/schema";

export const tags = defineCollection(
  "tags",
  {
    "label": fields.string({
      "required": true,
    }),
  },
  {
    "timestamps": true,
  }
);

export default tags;
