/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as VerifyEmailRouteImport } from './app/verify-email'
import { Route as RegisterRouteImport } from './app/register'
import { Route as MediaRouteImport } from './app/media'
import { Route as MagicLinkRouteImport } from './app/magic-link'
import { Route as LoginRouteImport } from './app/login'
import { Route as ForgotPasswordRouteImport } from './app/forgot-password'
import { Route as ContentRouteImport } from './app/content'
import { Route as IndexRouteImport } from './app/index'
import { Route as SettingsWebhooksRouteImport } from './app/settings.webhooks'
import { Route as SettingsSessionsRouteImport } from './app/settings.sessions'
import { Route as SettingsRolesRouteImport } from './app/settings.roles'
import { Route as SettingsI18nRouteImport } from './app/settings.i18n'
import { Route as SettingsHealthRouteImport } from './app/settings.health'
import { Route as SettingsContentTypesRouteImport } from './app/settings.content-types'
import { Route as SettingsAuditLogRouteImport } from './app/settings.audit-log'
import { Route as SettingsApiKeysRouteImport } from './app/settings.api-keys'
import { Route as OrganizationSettingsRouteImport } from './app/organization.settings'
import { Route as OrganizationMembersRouteImport } from './app/organization.members'
import { Route as OrganizationInvitationsRouteImport } from './app/organization.invitations'
import { Route as MediaMediaIdRouteImport } from './app/media.$mediaId'
import { Route as ContentCollectionNameRouteImport } from './app/content.$collectionName'
import { Route as R2faVerifyRouteImport } from './app/2fa.verify'
import { Route as R2faSetupRouteImport } from './app/2fa.setup'
import { Route as SettingsContentTypesVisualizerRouteImport } from './app/settings.content-types.visualizer'
import { Route as ContentCollectionNameNewRouteImport } from './app/content.$collectionName.new'
import { Route as ContentCollectionNameRecordIdRouteImport } from './app/content.$collectionName.$recordId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsI18nRoute = SettingsI18nRouteImport.update({
  id: '/settings/i18n',
  path: '/settings/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHealthRoute = SettingsHealthRouteImport.update({
  id: '/settings/health',
  path: '/settings/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContentTypesRoute = SettingsContentTypesRouteImport.update({
  id: '/settings/content-types',
  path: '/settings/content-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationInvitationsRoute = OrganizationInvitationsRouteImport.update({
  id: '/organization/invitations',
  path: '/organization/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/$mediaId',
  path: '/$mediaId',
  getParentRoute: () => MediaRoute,
} as any)
const ContentCollectionNameRoute = ContentCollectionNameRouteImport.update({
  id: '/$collectionName',
  path: '/$collectionName',
  getParentRoute: () => ContentRoute,
} as any)
const R2faVerifyRoute = R2faVerifyRouteImport.update({
  id: '/2fa/verify',
  path: '/2fa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faSetupRoute = R2faSetupRouteImport.update({
  id: '/2fa/setup',
  path: '/2fa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContentTypesVisualizerRoute =
  SettingsContentTypesVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => SettingsContentTypesRoute,
  } as any)
const ContentCollectionNameNewRoute =
  ContentCollectionNameNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ContentCollectionNameRoute,
  } as any)
const ContentCollectionNameRecordIdRoute =
  ContentCollectionNameRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => ContentCollectionNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/media': typeof MediaRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/2fa/setup': typeof R2faSetupRoute
  '/2fa/verify': typeof R2faVerifyRoute
  '/content/$collectionName': typeof ContentCollectionNameRouteWithChildren
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/organization/invitations': typeof OrganizationInvitationsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/content-types': typeof SettingsContentTypesRouteWithChildren
  '/settings/health': typeof SettingsHealthRoute
  '/settings/i18n': typeof SettingsI18nRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/content/$collectionName/$recordId': typeof ContentCollectionNameRecordIdRoute
  '/content/$collectionName/new': typeof ContentCollectionNameNewRoute
  '/settings/content-types/visualizer': typeof SettingsContentTypesVisualizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/media': typeof MediaRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/2fa/setup': typeof R2faSetupRoute
  '/2fa/verify': typeof R2faVerifyRoute
  '/content/$collectionName': typeof ContentCollectionNameRouteWithChildren
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/organization/invitations': typeof OrganizationInvitationsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/content-types': typeof SettingsContentTypesRouteWithChildren
  '/settings/health': typeof SettingsHealthRoute
  '/settings/i18n': typeof SettingsI18nRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/content/$collectionName/$recordId': typeof ContentCollectionNameRecordIdRoute
  '/content/$collectionName/new': typeof ContentCollectionNameNewRoute
  '/settings/content-types/visualizer': typeof SettingsContentTypesVisualizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/media': typeof MediaRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/2fa/setup': typeof R2faSetupRoute
  '/2fa/verify': typeof R2faVerifyRoute
  '/content/$collectionName': typeof ContentCollectionNameRouteWithChildren
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/organization/invitations': typeof OrganizationInvitationsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/content-types': typeof SettingsContentTypesRouteWithChildren
  '/settings/health': typeof SettingsHealthRoute
  '/settings/i18n': typeof SettingsI18nRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/content/$collectionName/$recordId': typeof ContentCollectionNameRecordIdRoute
  '/content/$collectionName/new': typeof ContentCollectionNameNewRoute
  '/settings/content-types/visualizer': typeof SettingsContentTypesVisualizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/media'
    | '/register'
    | '/verify-email'
    | '/2fa/setup'
    | '/2fa/verify'
    | '/content/$collectionName'
    | '/media/$mediaId'
    | '/organization/invitations'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/content-types'
    | '/settings/health'
    | '/settings/i18n'
    | '/settings/roles'
    | '/settings/sessions'
    | '/settings/webhooks'
    | '/content/$collectionName/$recordId'
    | '/content/$collectionName/new'
    | '/settings/content-types/visualizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/media'
    | '/register'
    | '/verify-email'
    | '/2fa/setup'
    | '/2fa/verify'
    | '/content/$collectionName'
    | '/media/$mediaId'
    | '/organization/invitations'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/content-types'
    | '/settings/health'
    | '/settings/i18n'
    | '/settings/roles'
    | '/settings/sessions'
    | '/settings/webhooks'
    | '/content/$collectionName/$recordId'
    | '/content/$collectionName/new'
    | '/settings/content-types/visualizer'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/media'
    | '/register'
    | '/verify-email'
    | '/2fa/setup'
    | '/2fa/verify'
    | '/content/$collectionName'
    | '/media/$mediaId'
    | '/organization/invitations'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/content-types'
    | '/settings/health'
    | '/settings/i18n'
    | '/settings/roles'
    | '/settings/sessions'
    | '/settings/webhooks'
    | '/content/$collectionName/$recordId'
    | '/content/$collectionName/new'
    | '/settings/content-types/visualizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  MediaRoute: typeof MediaRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  R2faSetupRoute: typeof R2faSetupRoute
  R2faVerifyRoute: typeof R2faVerifyRoute
  OrganizationInvitationsRoute: typeof OrganizationInvitationsRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsContentTypesRoute: typeof SettingsContentTypesRouteWithChildren
  SettingsHealthRoute: typeof SettingsHealthRoute
  SettingsI18nRoute: typeof SettingsI18nRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/i18n': {
      id: '/settings/i18n'
      path: '/settings/i18n'
      fullPath: '/settings/i18n'
      preLoaderRoute: typeof SettingsI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/health': {
      id: '/settings/health'
      path: '/settings/health'
      fullPath: '/settings/health'
      preLoaderRoute: typeof SettingsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/content-types': {
      id: '/settings/content-types'
      path: '/settings/content-types'
      fullPath: '/settings/content-types'
      preLoaderRoute: typeof SettingsContentTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/invitations': {
      id: '/organization/invitations'
      path: '/organization/invitations'
      fullPath: '/organization/invitations'
      preLoaderRoute: typeof OrganizationInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/content/$collectionName': {
      id: '/content/$collectionName'
      path: '/$collectionName'
      fullPath: '/content/$collectionName'
      preLoaderRoute: typeof ContentCollectionNameRouteImport
      parentRoute: typeof ContentRoute
    }
    '/2fa/verify': {
      id: '/2fa/verify'
      path: '/2fa/verify'
      fullPath: '/2fa/verify'
      preLoaderRoute: typeof R2faVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa/setup': {
      id: '/2fa/setup'
      path: '/2fa/setup'
      fullPath: '/2fa/setup'
      preLoaderRoute: typeof R2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/content-types/visualizer': {
      id: '/settings/content-types/visualizer'
      path: '/visualizer'
      fullPath: '/settings/content-types/visualizer'
      preLoaderRoute: typeof SettingsContentTypesVisualizerRouteImport
      parentRoute: typeof SettingsContentTypesRoute
    }
    '/content/$collectionName/new': {
      id: '/content/$collectionName/new'
      path: '/new'
      fullPath: '/content/$collectionName/new'
      preLoaderRoute: typeof ContentCollectionNameNewRouteImport
      parentRoute: typeof ContentCollectionNameRoute
    }
    '/content/$collectionName/$recordId': {
      id: '/content/$collectionName/$recordId'
      path: '/$recordId'
      fullPath: '/content/$collectionName/$recordId'
      preLoaderRoute: typeof ContentCollectionNameRecordIdRouteImport
      parentRoute: typeof ContentCollectionNameRoute
    }
  }
}

interface ContentCollectionNameRouteChildren {
  ContentCollectionNameRecordIdRoute: typeof ContentCollectionNameRecordIdRoute
  ContentCollectionNameNewRoute: typeof ContentCollectionNameNewRoute
}

const ContentCollectionNameRouteChildren: ContentCollectionNameRouteChildren = {
  ContentCollectionNameRecordIdRoute: ContentCollectionNameRecordIdRoute,
  ContentCollectionNameNewRoute: ContentCollectionNameNewRoute,
}

const ContentCollectionNameRouteWithChildren =
  ContentCollectionNameRoute._addFileChildren(
    ContentCollectionNameRouteChildren,
  )

interface ContentRouteChildren {
  ContentCollectionNameRoute: typeof ContentCollectionNameRouteWithChildren
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentCollectionNameRoute: ContentCollectionNameRouteWithChildren,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface MediaRouteChildren {
  MediaMediaIdRoute: typeof MediaMediaIdRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaMediaIdRoute: MediaMediaIdRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface SettingsContentTypesRouteChildren {
  SettingsContentTypesVisualizerRoute: typeof SettingsContentTypesVisualizerRoute
}

const SettingsContentTypesRouteChildren: SettingsContentTypesRouteChildren = {
  SettingsContentTypesVisualizerRoute: SettingsContentTypesVisualizerRoute,
}

const SettingsContentTypesRouteWithChildren =
  SettingsContentTypesRoute._addFileChildren(SettingsContentTypesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  MediaRoute: MediaRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  R2faSetupRoute: R2faSetupRoute,
  R2faVerifyRoute: R2faVerifyRoute,
  OrganizationInvitationsRoute: OrganizationInvitationsRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsContentTypesRoute: SettingsContentTypesRouteWithChildren,
  SettingsHealthRoute: SettingsHealthRoute,
  SettingsI18nRoute: SettingsI18nRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
